const DATE_LIKE =
  /\b(?:\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}|\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2})\b/;
const AMOUNT_LIKE = /(?:^|[^\d])[-+]?(?:\d{1,3}(?:,\d{3})*|\d+)\.\d{2}\b/;

export function countBankStatementLines(text: string): number {
  return text
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line.length > 0 && DATE_LIKE.test(line) && AMOUNT_LIKE.test(line))
    .length;
}

export function wrapBankStatement(text: string): string {
  const trimmed = text.trim();
  if (trimmed.includes("```bank-statement")) {
    return trimmed;
  }
  return `Please import these bank transactions:\n\n\`\`\`bank-statement\n${trimmed}\n\`\`\``;
}

const OUTPUT_CAP_HINT =
  /output cap|output budget|max_tokens|spent on thinking/i;

export function isOutputCapError(message: string): boolean {
  return OUTPUT_CAP_HINT.test(message);
}

export function publicChatErrorMessage(error: unknown): string {
  const message = error instanceof Error ? error.message : "";
  if (isOutputCapError(message)) {
    return "The assistant used its output budget on thinking and did not finish a reply. Try sending again.";
  }
  if (
    message.includes("Brain workflow ended without a reply") ||
    message.includes("ended without a reply")
  ) {
    return "The assistant stopped before finishing a reply. Try sending again.";
  }
  return "Failed to run chat workflow.";
}

export function formatRelativeTime(value: string | Date): string {
  const date = typeof value === "string" ? new Date(value) : value;
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  const diffMs = Date.now() - date.getTime();
  const minutes = Math.floor(diffMs / 60_000);
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days === 1) return "Yesterday";
  if (days < 7) return `${days}d ago`;
  return date.toLocaleDateString("en-NZ", {
    day: "numeric",
    month: "short",
  });
}

export function createTextRevealer(
  onAppend: (chunk: string) => void,
  charsPerFrame = 4
) {
  let pending = "";
  let frame: number | null = null;

  const pump = () => {
    if (!pending) {
      frame = null;
      return;
    }
    const next = pending.slice(0, charsPerFrame);
    pending = pending.slice(charsPerFrame);
    onAppend(next);
    frame = requestAnimationFrame(pump);
  };

  return {
    push(delta: string) {
      pending += delta;
      if (frame == null) {
        frame = requestAnimationFrame(pump);
      }
    },
    reset() {
      pending = "";
      if (frame != null) {
        cancelAnimationFrame(frame);
        frame = null;
      }
    },
    drain(): Promise<void> {
      return new Promise(resolve => {
        const wait = () => {
          if (!pending && frame == null) {
            resolve();
            return;
          }
          requestAnimationFrame(wait);
        };
        wait();
      });
    },
  };
}

const TITLE_MAX_LENGTH = 48;

const TITLE_LEAD_INS = [
  /^(please\s+)?(can you|could you|would you|will you)\s+/i,
  /^please\s+/i,
  /^i(?:'d| would)? (like|want|need) to\s+/i,
  /^(tell|show|give|help) me\s+(to\s+)?/i,
  /^what(?:'s| is| are| was| were)\s+/i,
  /^which\s+/i,
  /^how much(?: (?:did|have|do) i)?(?: (?:spend|spent|spending))?(?: on)?\s+/i,
  /^how many\s+/i,
  /^how (?:do i|can i|to)\s+/i,
  /^why (?:did|do|is|are|was|were)\s+/i,
  /^when (?:did|do|is|are|was|were)\s+/i,
  /^where (?:did|do|is|are|was|were)\s+/i,
  /^who (?:did|do|is|are|was|were)\s+/i,
  /^(set|create|add|make)\s+(a|an|the)\s+/i,
];

function firstSentence(text: string): string {
  const line = text.split(/\r?\n/).find(part => part.trim()) ?? text;
  const match = line.match(/^.+?[.?!](?:\s|$)/);
  return (match ? match[0] : line).trim();
}

function truncateAtWord(text: string, max: number): string {
  if (text.length <= max) return text;
  const slice = text.slice(0, max - 1);
  const cut = slice.lastIndexOf(" ");
  const base = (cut >= 20 ? slice.slice(0, cut) : slice).trimEnd();
  return `${base}…`;
}

/** Previous behaviour: first message, truncated to 50 characters. */
export function legacySessionTitle(message: string): string {
  const collapsed = message.trim().replace(/\s+/g, " ");
  if (!collapsed) return "New chat";
  if (collapsed.length <= 50) return collapsed;
  return `${collapsed.slice(0, 49).trimEnd()}…`;
}

export function isLegacyQuestionTitle(title: string, firstMessage: string): boolean {
  const collapsed = firstMessage.trim().replace(/\s+/g, " ");
  return title === collapsed || title === legacySessionTitle(firstMessage);
}

export function isAutoGeneratedTitle(title: string, firstMessage: string): boolean {
  if (!title || title === "New chat") return true;
  if (isLegacyQuestionTitle(title, firstMessage)) return true;
  return title === deriveSessionTitle(firstMessage);
}

export function sanitizeBrainTitle(raw: string): string | null {
  let text = raw.trim().split(/\r?\n/).find(line => line.trim()) ?? "";
  text = text
    .replace(/^(here(?:'s| is)(?: a)?(?: short)? title:\s*)/i, "")
    .replace(/^title:\s*/i, "")
    .replace(/^["'`]+|["'`]+$/g, "")
    .replace(/[?!.]+$/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (text.length < 2) return null;
  if (text.length > 80) {
    text = truncateAtWord(text, 60);
  }
  return text;
}

/**
 * Short topic title from the first user question, used in the thread header
 * and the session sidebar.
 */
export function deriveSessionTitle(message: string): string {
  const raw = message.trim();
  if (!raw) return "New chat";

  if (
    raw.includes("```bank-statement") ||
    /import(?:ing)? (?:my |the |these )?bank transactions/i.test(raw)
  ) {
    return "Bank statement import";
  }

  let text = firstSentence(raw).replace(/\s+/g, " ").trim();
  for (const pattern of TITLE_LEAD_INS) {
    text = text.replace(pattern, "");
  }
  text = text.replace(/[?!.]+$/g, "").replace(/\s+/g, " ").trim();
  if (!text) return "New chat";

  return truncateAtWord(
    text.charAt(0).toUpperCase() + text.slice(1),
    TITLE_MAX_LENGTH
  );
}

export type SessionGroup = "Today" | "Previous 7 days" | "Earlier";

export function sessionGroupLabel(value: string | Date): SessionGroup {
  const date = typeof value === "string" ? new Date(value) : value;
  const startOfToday = new Date();
  startOfToday.setHours(0, 0, 0, 0);
  const startOfWeek = new Date(startOfToday);
  startOfWeek.setDate(startOfWeek.getDate() - 7);

  if (date >= startOfToday) return "Today";
  if (date >= startOfWeek) return "Previous 7 days";
  return "Earlier";
}
