import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faSearch,
  faChartLine,
  faBriefcase,
  faBook,
  faBookmark,
  faList,
  faProjectDiagram,
  faChartBar,
  faUsers,
  faCog,
  faDownload,
  faUpload,
  faFile,
  faClock,
  faExclamationTriangle,
  faPlus,
  faMinus,
  faBuilding,
  faArrowLeft,
  faArrowRight,
  faInbox,
  faCheckCircle,
  faRepeat,
  faArrowRotateLeft,
  faTag,
  faCheck,
  faCoins,
  faHourglassHalf,
  faFileAlt,
  faEllipsisH,
  faShield,
  faShieldAlt,
  faLock,
  faStar,
  faPlug,
  faUser,
  faHome,
  faMagnifyingGlassChart,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faClipboardCheck,
  faFolderOpen,
  faShieldHalved,
  faBars,
  faSlidersH,
  faGlobe,
  faArrowUp,
  faChartPie,
  faBookBookmark,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faXmark,
  faPen,
  faPencil,
  faShare,
  faFileExport,
  faLocationDot,
  faCircle,
  faMicrophone,
  faKeyboard,
  faCircleExclamation,
  faTriangleExclamation,
  faListCheck,
  faEnvelope,
  faCopy,
  faCloudArrowUp,
  faInfoCircle,
  faPlay,
  faCircleCheck,
  faSignal,
  faHighlighter,
  faTrash,
  faEllipsisVertical,
  faRightFromBracket,
  faCity,
  faTags,
  faSave,
  faTimes,
  faDesktop,
  faEye,
  faFileContract,
  faMapMarkerAlt,
  faCalendarAlt,
  faMap,
  faArchive,
  faSync,
  faPhone,
  faMailBulk,
  faSort,
  faComment,
  faRobot,
  faPaperPlane,
  faBolt,
  faCalendar,
} from "@fortawesome/free-solid-svg-icons";

export type FontAwesomeIconType = keyof typeof fontAwesomeIcons;
export type IconType = FontAwesomeIconType;

const fontAwesomeIcons = {
  search: faSearch,
  home: faHome,
  qualityChecks: faMagnifyingGlassChart,
  expertReviews: faClipboardCheck,
  qualityProfiles: faShieldHalved,
  qualityLogs: faChartPie,
  library: faBookBookmark,
  dashboard: faChartLine,
  clients: faBriefcase,
  rulebooks: faBook,
  references: faBookmark,
  requirements: faList,
  workflows: faProjectDiagram,
  analytics: faChartBar,
  users: faUsers,
  settings: faCog,
  download: faDownload,
  upload: faUpload,
  file: faFile,
  clock: faClock,
  warning: faExclamationTriangle,
  plus: faPlus,
  minus: faMinus,
  building: faBuilding,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  inbox: faInbox,
  checklist: faCheckCircle,
  repeat: faRepeat,
  arrowRotateLeft: faArrowRotateLeft,
  tag: faTag,
  check: faCheck,
  checkmark: faCheck,
  credits: faCoins,
  time: faHourglassHalf,
  documents: faFileAlt,
  more: faEllipsisH,
  shield: faShield,
  shieldAlt: faShieldAlt,
  lock: faLock,
  star: faStar,
  integrations: faPlug,
  user: faUser,
  folderOpen: faFolderOpen,
  bars: faBars,
  sliders: faSlidersH,
  globe: faGlobe,
  arrowUp: faArrowUp,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  xmark: faXmark,
  xMark: faXmark,
  pen: faPen,
  pencil: faPencil,
  share: faShare,
  fileExport: faFileExport,
  locationDot: faLocationDot,
  circle: faCircle,
  list: faList,
  microphone: faMicrophone,
  keyboard: faKeyboard,
  exclamationCircle: faCircleExclamation,
  exclamationTriangle: faExclamationTriangle,
  triangleExclamation: faTriangleExclamation,
  listCheck: faListCheck,
  zoomIn: faMagnifyingGlassPlus,
  zoomOut: faMagnifyingGlassMinus,
  envelope: faEnvelope,
  copy: faCopy,
  cloudUpload: faCloudArrowUp,
  infoCircle: faInfoCircle,
  play: faPlay,
  circleCheck: faCircleCheck,
  signal: faSignal,
  highlighter: faHighlighter,
  trash: faTrash,
  ellipsisVertical: faEllipsisVertical,
  signOut: faRightFromBracket,
  city: faCity,
  tags: faTags,
  save: faSave,
  times: faTimes,
  desktop: faDesktop,
  eye: faEye,
  chartLine: faChartLine,
  fileContract: faFileContract,
  mapMarkerAlt: faMapMarkerAlt,
  calendarAlt: faCalendarAlt,
  chartBar: faChartBar,
  map: faMap,
  archive: faArchive,
  sync: faSync,
  phone: faPhone,
  mailBulk: faMailBulk,
  sort: faSort,
  comment: faComment,
  robot: faRobot,
  paperPlane: faPaperPlane,
  bolt: faBolt,
  calendar: faCalendar,
  cog: faCog,
};

interface IconProps {
  icon: IconType;
  className?: string;
}

export const Icon = ({ icon, className }: IconProps) => {
  return (
    <FontAwesomeIcon
      icon={fontAwesomeIcons[icon as FontAwesomeIconType]}
      className={className}
    />
  );
};
